---
title: "PCRA 3"
author: "Josh Winnes"
date: "`r Sys.Date()`"
output: html_document
---

```{r include=FALSE}
library(tidyverse)
library(janitor)
```

## ***Part 1***

### A)

```{r include = FALSE, echo=FALSE, message=FALSE, warning=FALSE}
students <- read_csv('https://pos.it/r4ds-students-csv', na=c("N/A", ""))
students |> 
  janitor::clean_names() |>
  mutate(
    meal_plan = factor(meal_plan),
    age = parse_number(if_else(age=="five", "5", age))
    )
```

```{r echo=TRUE, message=FALSE, warning=FALSE}
read_csv( "A line to skip \n 1,2,3 \n 4,5,6",
          skip = 1,
          col_names = c("A", "B", "C"))
```

### B)

To read a `data.xslx`, you would need to use either the `read_xslx()` function or the `read_excel()` function in the `readxl` library.

### C)

```{r echo=TRUE, message=FALSE, warning=FALSE}
# Exercise 20.3.6.2
library(googlesheets4)
gs4_deauth()
url <- "https://docs.google.com/spreadsheets/d/1yc5gL-a2OOBr8M7B3IsDNX5uR17vBHOyWZq6xSTG2G8/edit?gid=0#gid=0"
sheet <- read_sheet(url, col_types="cd")
sheet
```

## ***Part 2***

No questions at the moment.
